// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGhQaQ527hvbfzWve4ZoGjGhZVHP497Os',
    appId: '1:328636166233:web:b03d7e812ac7bd9df1c148',
    messagingSenderId: '328636166233',
    projectId: 'anrear-8e2f6',
    authDomain: 'anrear-8e2f6.firebaseapp.com',
    storageBucket: 'anrear-8e2f6.appspot.com',
    measurementId: 'G-S0ZMSQSWM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCOKrf8BfknqaAXBhRcFf_2XuDMleBM10',
    appId: '1:328636166233:android:8b70e313beaa388bf1c148',
    messagingSenderId: '328636166233',
    projectId: 'anrear-8e2f6',
    storageBucket: 'anrear-8e2f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9gwPtoX8UBiRHqAfP9t1wbYEMuauBHo0',
    appId: '1:328636166233:ios:b91707cd54c0a408f1c148',
    messagingSenderId: '328636166233',
    projectId: 'anrear-8e2f6',
    storageBucket: 'anrear-8e2f6.appspot.com',
    iosClientId: '328636166233-134ho1fkghg59739i9ab5najgv3eci35.apps.googleusercontent.com',
    iosBundleId: 'com.anrear.thesuitch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9gwPtoX8UBiRHqAfP9t1wbYEMuauBHo0',
    appId: '1:328636166233:ios:537e40abaf4b889ef1c148',
    messagingSenderId: '328636166233',
    projectId: 'anrear-8e2f6',
    storageBucket: 'anrear-8e2f6.appspot.com',
    iosClientId: '328636166233-fd0gtf975poh9ajh3l5pd9o3hthraocu.apps.googleusercontent.com',
    iosBundleId: 'com.example.anrear',
  );
}
